//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int id { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> fechaCita { get; set; }
        public Nullable<System.DateTime> horaCita { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idTipoCita { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual TipoCita TipoCita { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
