//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> idTelf { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual TelefonoUsuario TelefonoUsuario { get; set; }
    }
}
